### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by st-clair-clarke** [joseluisq/nano-crypto#3]
Hi, the package does not work in angular 8 or 9. Are you considering an update?

Cheers

**Comment by joseluisq** [comment]
I don't know what do you mean, this package uses requires nodejs is not posted to web. If you want it feel free to send a PR.

**Comment by st-clair-clarke** [comment]
Should your package work with typescript and angular 2 (8 or 9)? I can't get it to work.

**Comment by joseluisq** [comment]
> Should your package work with typescript and angular 2 (8 or 9)? I can't get it to work.

It works with Typescript but It doesn't on the web. It's a NodeJS package (server side only).
Take at look at [Browser API](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) if you want to port this package to the web feel free to send a PR.
Unfortunately I have no time for that.

**Comment by joseluisq** [comment]
Since the underlying dependency https://github.com/ai/nanoid/blob/master/random.browser.js supports browser. It would be easy to port it to web as well.

**Comment by joseluisq** [comment]
Because of that https://github.com/joseluisq/nano-crypto/blob/ca7694aa435f102ecbc225d481abe2721477ff9d/src/index.ts#L1

**Comment by joseluisq** [comment]
Hey!
There is some kind of progress on browser support right now (`random`):

![image](https://user-images.githubusercontent.com/1700322/74288839-c90a8b80-4d2d-11ea-8451-3ee2f287c09e.png)

In the future it would look like:

**Browser**:
```ts
import { random } from "nano-crypto/random.browser" // (494b gzipped)
// Angular, React, whatever...
```

**Node**:
```ts
import { random } from "nano-crypto/random"
// Node apps, etc
```

Stay tuned!

**Comment by joseluisq** [comment]
Done first [v1.0.0](https://github.com/joseluisq/nano-crypto/releases/tag/v1.0.0) which includes browser support for `random` described above.

**Comment by st-clair-clarke** [comment]
Thanks Jose. Appreciate the effort.
